### ISSUE TITLE
WelcomeMessage and LoginResult errors

### ISSUE THREAD

**Issue by cfunkz** [p0t4t0sandwich/ampapi-python#14]
WelcomeMessage needs to be added to types.py Instance class and IADSInstance as otherwise it gives error. After adding that, LoginResult now brings out error that is missing multiple arguments like Status, Reason, SupportTitle, SupportURL? 
`Python 3.12.1`
`v2.5.1.8, built 03/09/2024 11:47`

**Comment by p0t4t0sandwich** [comment]
`LoginResult` has not changed at all, I don't see Status, Reason, SupportTitle, or SupportURL when querying `API/Core/Login`. There could be a formatting error in `types.py` after you made the changes to IADSInstance

**Comment by p0t4t0sandwich** [comment]
`WelcomeMessage`  also doesn't appear to be part of `IADSInstance`, but rather just a regular `Instance` object.
Please replicate the issue and provide a stacktrace in case there's just a difference in our setups/reconfigured instances so I can add any new properties properly.

**Comment by p0t4t0sandwich** [comment]
Just pushed a release that should hopefully fix things. Feel free to re-open this issue if you're able to replicate the LoginResult issue
