### ISSUE TITLE
AMP 2.4.7 errors on ADSModule.GetInstances()

### ISSUE THREAD

**Issue by Keiron-Beadle** [p0t4t0sandwich/ampapi-python#7]
<img width="841" alt="image" src="https://github.com/p0t4t0sandwich/ampapi-py/assets/56656042/8c51502b-e1f2-4b15-bfb0-9018108522ef">

AMP Version: 2.4.7 - 20240109.1

Getting the instance list gave me a few errors, I'll post my own PR in a few minutes that I used to fix the issues. Obviously feel free to check it over and do it another way :)

**Comment by Keiron-Beadle** [comment]
https://github.com/p0t4t0sandwich/ampapi-py/pull/8

Here are my proposed changes to fix, should be tested in your environment, as this fixed my problems, but might not be a widespread issue.

**Comment by p0t4t0sandwich** [comment]
Awesome, I'll give this a run-through when I get the chance. I probably didn't catch this while testing due to how old/new AMP instances retain metadata. The old instances sometimes don't get certain properties applied to them until they're reconfigured, or just not at all in some cases.

**Comment by Keiron-Beadle** [comment]
Oh really? I had no idea about that metadata thing, sounds super annoying to test with :(
